name: CI

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Run unit tests
        run: pwsh run_tests.ps1
